networks:
  deploy-dev:
    driver: bridge
services:
#  app:
#    container_name: hub-service
#    build:
#      context: .
#      dockerfile: WebApi/Dockerfile
#    environment:
#      ASPNETCORE_ENVIRONMENT: Production
#      ASPNETCORE_HTTP_PORTS: 8084
#    ports:
#      - "8084:8084"
#    networks:
#      - deploy-dev
#    depends_on:
#      - hub-db
  hub-db:
    container_name: hub-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hub_db
      PGPORT: 5437
    ports:
      - "5437:5437"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data: